#Q.1) Calculate the total revenue generated by two product categories in a store 
"""Input: category1_revenue = np.array([500, 600, 700, 550]) 
category2_revenue = np.array([450, 700, 800, 600]) """

# Import the NumPy library
import numpy as np  

# Revenue data for Category 1 across four periods
category1_revenue = np.array([500, 600, 700, 550])  

# Revenue data for Category 2 across the same four periods
category2_revenue = np.array([450, 700, 800, 600])  

# Calculate total revenue by adding Category 1 and Category 2 revenues
total_revenue = category1_revenue + category2_revenue

# Display the total revenue
print("Total Revenue:", total_revenue)

"""
OUTPUT : Total Revenue: [ 950 1300 1500 1150]
"""
